///*
// * This file is auto generated by Cognizant TestRobot
// * Tue Oct 17 13:03:35 IST 2017
// */
//
//package com.dnb.gcmsOnline.controller;
//
//import static org.junit.Assert.assertEquals;
//import static org.mockito.Matchers.any;
//import static org.mockito.Matchers.anyString;
//import static org.mockito.Mockito.doReturn;
//import static org.mockito.Mockito.doThrow;
//import static org.mockito.Mockito.mock;
//
//import org.junit.Before;
//import org.junit.Test;
//import org.mockito.InjectMocks;
//import org.mockito.Mock;
//import org.mockito.MockitoAnnotations;
//import org.powermock.core.classloader.annotations.PrepareForTest;
//import org.springframework.ui.ModelMap;
//import org.springframework.web.servlet.mvc.support.RedirectAttributes;
//
//import com.dnb.gcms.common.domain.DunsSearchInfo;
//import com.dnb.gcms.search.service.SearchServiceImpl;
//
////@SuppressStaticInitializationFor({<comma-separated fully qualified class names in double quotes>})
//@PrepareForTest({RedirectAttributes.class,HomeController.class,DunsSearchInfo.class,SearchServiceImpl.class})
//public class HomeControllerTest {
//
//  @InjectMocks
//  HomeController homeController0;
//  
//  @Mock(name="searchServiceImpl")
//  SearchServiceImpl searchServiceImpl0;
//
//  @Before
//  public void setUp()  {
//      MockitoAnnotations.initMocks(this);
//  }
//    /**
//     * Test case for path 1
//     */
//  @Test
//  public void dunsSearchTest0()  throws Throwable  {
//      DunsSearchInfo dunsSearchInfo0 = mock(DunsSearchInfo.class);
//      ModelMap modelMap0 = new ModelMap();
//      
//      RedirectAttributes redirectAttributes0 = mock(RedirectAttributes.class);
//      doReturn(dunsSearchInfo0).when(searchServiceImpl0).getSearchResult(anyString());
//      RedirectAttributes redirectAttributes1 = mock(RedirectAttributes.class);
//      doReturn(redirectAttributes1).when(redirectAttributes0).addFlashAttribute(anyString() , any());
//      
//      // Invoke method under test
//      String string0 = homeController0.dunsSearch(dunsSearchInfo0, modelMap0, redirectAttributes0);
//      assertEquals("search-results", string0);
//  }
//
//    /**
//     * Test case for path 1
//     */
//  @Test
//  public void dunsSearchTest1()  throws Throwable  {
//      DunsSearchInfo dunsSearchInfo0 = null;
//      ModelMap modelMap0 = new ModelMap();
//      
//      RedirectAttributes redirectAttributes0 = mock(RedirectAttributes.class);
//      doThrow(Exception.class).when(searchServiceImpl0).getSearchResult(anyString());
//      
//      // Invoke method under test
//      String string0 = homeController0.dunsSearch(dunsSearchInfo0, modelMap0, redirectAttributes0);
//      assertEquals("search-results", string0);
//  }
//}
